name: Spoony's site
description: enjoy
meta_description: "personal site"
bio: Keep going

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://localhost:4000'
google_analytics: UA-59167977-1

# Details for the RSS feed generator
url:            'http://xiaoqing.info'
author:         'Spoony'
